"""API response models for all public backend endpoints.

These models are intentionally compatibility-friendly: they keep optional
fields for legacy/degraded responses while still enforcing typed schemas.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class ReasoningChainResponse(BaseModel):
    """Reasoning chain shown in the AI reasoning panel."""

    cause: str = ""
    trend: str = ""
    prediction: str = ""
    reasoning: str = ""
    action: str = ""
    status: str = ""


class CommunicationResponse(BaseModel):
    """Communication payload generated by the communicator agent."""

    attendee_notification: str = ""
    staff_alert: str = ""
    signage_message: str = ""
    narration: str = ""
    reasoning_chain: ReasoningChainResponse = Field(default_factory=ReasoningChainResponse)


class PredictionResponse(BaseModel):
    """Prediction result for a zone."""

    zone_id: str
    zone_name: str = ""
    current_pct: float = 0.0
    predicted_pct: float = 0.0
    confidence: float = 0.0
    uncertainty_reason: str = ""
    risk_trajectory: str = "stable"
    minutes_to_critical: int | None = None


class DecisionResponse(BaseModel):
    """Operational decision generated by the decision agent."""

    action_type: str
    target_zone: str
    instruction: str
    priority: str
    expected_impact: str


class ImpactResponse(BaseModel):
    """Observed impact from prior operational actions."""

    action_instruction: str = ""
    target_zone: str = ""
    before_pct: float = 0.0
    after_pct: float = 0.0
    change_pct: float = 0.0
    resolved: bool = False
    resolved_at: str | None = None


class PipelineRunResponse(BaseModel):
    """Full pipeline output returned by /pipeline/latest."""

    run_id: str | None = None
    run_at: str | None = None
    source: str | None = None
    pipeline_health: str | None = None
    hotspots: list[str] = Field(default_factory=list)
    cascade_zones: list[str] = Field(default_factory=list)
    predictions: list[PredictionResponse] = Field(default_factory=list)
    decisions: list[DecisionResponse] = Field(default_factory=list)
    impacts: list[ImpactResponse] = Field(default_factory=list)
    communication: CommunicationResponse = Field(default_factory=CommunicationResponse)
    confidence_overall: float = 0.0
    pipeline_duration_ms: int = 0
    pipeline_latency_ms: int = 0
    fallback_used: bool = False
    metrics: dict[str, Any] = Field(default_factory=dict)
    analyst_summary: str | None = None
    operations_summary: str | None = None
    phase_status: dict[str, Any] = Field(default_factory=dict)
    fallback_reason: str | None = None


class PipelineHistoryItemResponse(BaseModel):
    """Compact pipeline run item returned by /pipeline/history."""

    run_id: str | None = None
    run_at: str | None = None
    source: str | None = None
    hotspots: list[str] = Field(default_factory=list)
    decisions_count: int = 0
    confidence_overall: float | None = None
    narration: str | None = None
    pipeline_duration_ms: int | None = None


class ZoneResponse(BaseModel):
    """Single venue zone state."""

    zone_id: str
    name: str
    type: str | None = None
    tick_id: str | None = None
    occupancy_pct: float = 0.0
    flow_rate: float = 0.0
    queue_depth: int = 0
    queue_wait_minutes: float | None = None
    risk_level: str = "low"
    trend: str = "stable"
    capacity: int = 0
    current_count: int = 0
    adjacent_zones: list[str] = Field(default_factory=list)
    updated_at: str | datetime | None = None


class HighestRiskZoneResponse(BaseModel):
    """Highest risk zone summary for dashboard stats."""

    zone_id: str = ""
    name: str = ""
    occupancy_pct: float = 0.0
    risk_level: str = "low"


class AlertItemResponse(BaseModel):
    """Alert item returned by /alerts."""

    alert_id: str | None = None
    zone_id: str | None = None
    zone_name: str | None = None
    severity: str | None = None
    occupancy_pct: float | None = None
    message: str | None = None
    created_at: str | datetime | None = None
    resolved: bool | None = None
    resolved_at: str | datetime | None = None


class ActivityEventItemResponse(BaseModel):
    """Activity feed event item."""

    event_id: str | None = None
    event_type: str | None = None
    message: str | None = None
    zone_id: str | None = None
    severity: str | None = None
    timestamp: str | datetime | None = None
    color: str | None = None


class ZonesResponse(BaseModel):
    """Response for GET /zones."""

    zones: list[ZoneResponse] = Field(default_factory=list)
    count: int = 0
    status: str | None = None


class ZoneSummaryResponse(BaseModel):
    """Response for GET /zones/summary."""

    total_attendees: int | None = None
    avg_occupancy_pct: float | None = None
    zone_count: int | None = None
    risk_distribution: dict[str, int] | None = None
    error: str | None = None


class PipelineLatestResponse(BaseModel):
    """Response for GET /pipeline/latest."""

    message: str | None = None
    run_id: str | None = None
    run_at: str | None = None
    source: str | None = None
    pipeline_health: str | None = None
    hotspots: list[str] = Field(default_factory=list)
    cascade_zones: list[str] = Field(default_factory=list)
    predictions: list[PredictionResponse] = Field(default_factory=list)
    decisions: list[DecisionResponse] = Field(default_factory=list)
    impacts: list[ImpactResponse] = Field(default_factory=list)
    communication: CommunicationResponse = Field(default_factory=CommunicationResponse)
    confidence_overall: float = 0.0
    pipeline_duration_ms: int = 0
    pipeline_latency_ms: int = 0
    fallback_used: bool = False
    metrics: dict[str, Any] = Field(default_factory=dict)
    analyst_summary: str | None = None
    operations_summary: str | None = None
    phase_status: dict[str, Any] = Field(default_factory=dict)
    fallback_reason: str | None = None


class PipelineHistoryResponse(BaseModel):
    """Response for GET /pipeline/history."""

    runs: list[PipelineHistoryItemResponse] = Field(default_factory=list)
    count: int = 0


class SimulationStatusResponse(BaseModel):
    """Response for simulation status and heartbeat endpoints."""

    message: str | None = None
    phase: str | None = None
    phase_display: str | None = None
    simulated_minutes: int | None = None
    simulation_progress_pct: float | None = None
    is_paused: bool | None = None
    status: str | None = None
    runner_id: str | None = None
    last_seen: str | datetime | None = None
    cycles_completed: int | None = None
    current_phase: str | None = None
    simulation_speed: float | str | None = None


class StatsResponse(BaseModel):
    """Response for GET /stats."""

    total_attendees: int
    active_alerts: int
    avg_queue_wait_min: float
    highest_risk_zone: HighestRiskZoneResponse
    last_pipeline_run: str
    pipeline_source: str
    pipeline_latency_ms: int = 0
    confidence_overall: float = 0.0
    pipeline_runs: int = 0
    fallback_used: bool = False


class AlertsResponse(BaseModel):
    """Response for GET /alerts."""

    alerts: list[AlertItemResponse] = Field(default_factory=list)
    count: int = 0


class ActivityFeedResponse(BaseModel):
    """Response for GET /activity-feed."""

    events: list[ActivityEventItemResponse] = Field(default_factory=list)
    count: int = 0


class HealthServicesResponse(BaseModel):
    """Readiness breakdown per external dependency."""

    firestore: str
    gemini: str


class HealthResponse(BaseModel):
    """Response model for root, liveness, and readiness endpoints."""

    service: str | None = None
    version: str | None = None
    mode: str | None = None
    status: str
    timestamp: str | None = None
    simulation: str | None = None
    simulation_phase: str | None = None
    simulation_cycles: int | None = None
    simulation_speed: str | None = None
    pipeline: str | None = None
    websocket_connections: int | None = None
    last_pipeline_run: str | None = None
    zones_active: int | None = None
    endpoints: list[str] | None = None
    services: HealthServicesResponse | None = None
    error: str | None = None


class MessageResponse(BaseModel):
    """Simple message response payload."""

    message: str


class PhaseSetResponse(BaseModel):
    """Response payload for /simulation/phase."""

    message: str
    phase: str


class TriggerPipelineResponse(BaseModel):
    """Response for manually triggering a pipeline run."""

    message: str
    check: str


class SimulationPlayResponse(BaseModel):
    """Response for /simulation/play."""

    message: str
    run_for_seconds: int


class LogsRecentResponse(BaseModel):
    """Response for GET /logs/recent."""

    logs: list[str] = Field(default_factory=list)
    message: str | None = None
    total_lines: int | None = None
    returned: int | None = None


class SystemInfoResponse(BaseModel):
    """Response for GET /system/info."""

    ai_agents: int = 4
    prediction_horizon_minutes: int = 10
    pipeline_interval_sec: int = 30
    fallback_enabled: bool = True
    data_source: str = "simulation + firestore"
    simulation_enabled: bool = True
    websocket_enabled: bool = True
