[pytest]
testpaths = tests
addopts = -v --tb=short --cov=app --cov-report=term-missing --cov-fail-under=55
filterwarnings =
	ignore:Type google\._upb\._message\.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new:DeprecationWarning
	ignore:Type google\._upb\._message\.ScalarMapContainer uses PyType_Spec with a metaclass that has custom tp_new:DeprecationWarning
